# Generated by Django 3.1.7 on 2021-03-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0002_account_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
