# Generated by Django 3.2 on 2021-05-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0003_auto_20210310_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Bank Account', 'Bank Account'), ('Loan', 'Loan'), ('Foreign Bank', 'Foreign Bank')], default='Bank Account', max_length=200),
        ),
    ]
